version: '3'
services:
  app:
    build: ./
    command: python main.py run -h 0.0.0.0
    depends_on:
      - db
  nginx:
    build:
      dockerfile: nginx/Dockerfile
      context: .
    ports:
      - 5000:80
    depends_on:
      - app
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: "sna_project"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    restart: "no"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/sna_project.sql:/docker-entrypoint-initdb.d/create_tables.sql


volumes:
  postgres_data: